### ISSUE TITLE
NoClassDefFoundError org.gradle.api.internal.CollectionCallbackActionDecorator

### ISSUE THREAD

**Issue by stephen-smith** [stevesaliman/gradle-cobertura-plugin#166]
```
org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type net.sal
iman.gradle.plugin.cobertura.CoberturaReportsImpl_Decorated.
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:53)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstanti
ator.java:36)
        at net.saliman.gradle.plugin.cobertura.GenerateReportTask$1.create(GenerateReportTask.groovy:52)
        at net.saliman.gradle.plugin.cobertura.GenerateReportTask$1.create(GenerateReportTask.groovy)
        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:230)
        at org.gradle.util.SingleMessageLogger$whileDisabled.call(Unknown Source)
        at net.saliman.gradle.plugin.cobertura.GenerateReportTask.createReports(GenerateReportTask.groovy:49
)
        at net.saliman.gradle.plugin.cobertura.GenerateReportTask.<init>(GenerateReportTask.groovy:42)
        at net.saliman.gradle.plugin.cobertura.GenerateReportTask_Decorated.<init>(Unknown Source)
        at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiat
or.java:81)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:123)
        ... 120 more
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/internal/CollectionCallbackActionDecorator
        at net.saliman.gradle.plugin.cobertura.CoberturaReportsImpl.<init>(CoberturaReportsImpl.java:12)
        at net.saliman.gradle.plugin.cobertura.CoberturaReportsImpl_Decorated.<init>(Unknown Source)
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
        ... 130 more
```

```
% gradle --version

------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.16
Ant:          Apache Ant(TM) version 1.10.5 compiled on March 28 2019
JVM:          1.8.0_232 (Private Build 25.232-b09)
OS:           Linux 5.3.0-22-generic amd64
```

That's the latest version available on Ubuntu Bionic.

Maybe related to #156 ?

I'm trying to use version "3.0.0" as the Usage says, but if I need to use an older version for Gradle 4.4.1 support, that's fine, I just need to know which one.

**Comment by stephen-smith** [comment]
Using version 2.5.4 worked for me.  If Gradle 4.4.1 compatibility isn't a feature of version 3.0.0, please close.

**Comment by stevesaliman** [comment]
As of Version 3.0.0 of the plugin the minimum support version of Gradle is 5.1.  To use older versions of Gradle, you'll need version 2.x of the plugin.  The last release of the 2.x series is 2.6.1.
