### ISSUE TITLE
NullPointerException on applying plugin after groovy plugin (2.2.0-SNAPSHOT)

### ISSUE THREAD

**Issue by szpak** [stevesaliman/gradle-cobertura-plugin#37]
Using recent snapshot I've got NPE when cobertura plugin is applied after groovy plugin (it works fine when applied before).

```
Applying cobertura plugin to gradle-pitest-plugin
creating extension

FAILURE: Build failed with an exception.

* Where:
Build file '/home/foo/gradle-pitest-plugin/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating root project 'gradle-pitest-plugin'.
> Could not create an instance of type net.saliman.gradle.plugin.cobertura.CoberturaExtension_Decorated.
```

with root cause:

```
Caused by: java.lang.NullPointerException
    at net.saliman.gradle.plugin.cobertura.CoberturaExtension_Decorated.getProperty(Unknown Source)
    at net.saliman.gradle.plugin.cobertura.CoberturaExtension$_closure3.doCall(CoberturaExtension.groovy:220)
    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:58)
    at org.gradle.api.internal.Actions$FilteredAction.execute(Actions.java:203)
    at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
    at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
    at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:126)
    at org.gradle.api.DomainObjectCollection$withType.call(Unknown Source)
    at net.saliman.gradle.plugin.cobertura.CoberturaExtension.<init>(CoberturaExtension.groovy:219)
    at net.saliman.gradle.plugin.cobertura.CoberturaExtension_Decorated.<init>(Unknown Source)
    at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:39)
    ... 70 more
```

**Comment by miguno** [comment]
For the record: In my case (Gradle 1.12, gradle-cobertura-plugin 2.2.8) the fix was to add `classpath 'org.codehaus.groovy:groovy-backports-compat23:2.3.5'` to `buildscript { dependencies { ... }}` as described in the [Usage](https://github.com/stevesaliman/gradle-cobertura-plugin/blob/master/usage.md) page.
