### ISSUE TITLE
Unable to instrument file

### ISSUE THREAD

**Issue by ctmay4** [stevesaliman/gradle-cobertura-plugin#57]
I am having problems getting the plugin to work.  The Jacoco plugin works fine, but I can't get Cobertura to work.

Here is what I added in build.gradle (using the 2.0 version of the Gradle wrapper and running under Java 8):

    buildscript {
        repositories {
            jcenter()
        }

        dependencies {
            classpath 'net.saliman:gradle-cobertura-plugin:2.2.4'
            classpath 'org.gradle.api.plugins:gradle-nexus-plugin:0.7'
        }
    }
    apply plugin: 'cobertura'

and here is the error I get.  It is repeated for every file it tries to instrument.

    C:\Prj\seerapi-client-java>gradlew clean cobertura
    :clean
    :coberturaReport UP-TO-DATE
    :compileJava
    :processResources UP-TO-DATE
    :classes
    :instrument
    Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
    Unable to instrument file C:\Prj\seerapi-client-java\build\instrumented_classes\com\imsweb\seerapi\client\cs\CsCodeValidity.class
    java.lang.IllegalArgumentException
            at org.objectweb.asm.ClassReader.<init>(Unknown Source)
            at org.objectweb.asm.ClassReader.<init>(Unknown Source)
            at org.objectweb.asm.ClassReader.<init>(Unknown Source)
            at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:147)
            at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:121)
            at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:234)
            at net.sourceforge.cobertura.instrument.Main.addInstrumentationToSingleClass(Main.java:298)
            at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:307)
            at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
            at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
            at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
            at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
            at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
            at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
            at net.sourceforge.cobertura.instrument.Main.parseArguments(Main.java:399)

**Comment by stevesaliman** [comment]
I just released version 2.2.7 of the plugin which uses version 2.1.1 of Cobertura, which in turn updates some of the other libraries used including our problem child, ASM.  Is this still a problem in version 2.2.7?

**Comment by stevesaliman** [comment]
I think we've traced this to ASM problems, which are documented in this and other issues in the project.  Closing.
