### ISSUE TITLE
Unusually low coverage reported

### ISSUE THREAD

**Issue by TAGC** [stevesaliman/gradle-cobertura-plugin#67]
I'm not sure if this is a problem with the plugin or with my configuration.

I'm trying to configure a project to produce code coverage reports. I've tested with Gradle's built-in Jacoco plugin and with Cobertura using this plugin (v2.2.5).

My system is setup as follows:

    Gradle:       2.2.1
    Groovy:       2.3.6
    Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
    JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
    OS:           Mac OS X 10.10.1 x86_64

I'm developing in pure Groovy.

Jacoco works as expected and gives a plausible coverage of 68% (by instructions). Cobertura gives a much lower (line) coverage of 35%. Large sections of the code are reported as not being tested even though unit tests exist for them and Jacoco reports that they are covered.

A lot more information is provided at [this StackOverflow page](http://stackoverflow.com/questions/27726084/unusually-low-test-coverage-reported-when-using-cobertura-with-gradle-and-groovy).

**Comment by stevesaliman** [comment]
Out of curiosity, what happens if you configure the plugin to use version 2.1 of Cobertura?

**Comment by TAGC** [comment]
I try to set the version like this:

```
cobertura {
    // Force version 2.1.0
    coberturaVersion = '2.1.0-SNAPSHOT'
}
```

I get an unresolved dependencies exception like this:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instrument'.
> Could not resolve all dependencies for configuration ':cobertura'.
   > Could not find net.sourceforge.cobertura:cobertura:2.1.0-SNAPSHOT.
     Searched in the following locations:
         https://repo1.maven.org/maven2/net/sourceforge/cobertura/cobertura/2.1.0-SNAPSHOT/maven-metadata.xml
         https://repo1.maven.org/maven2/net/sourceforge/cobertura/cobertura/2.1.0-SNAPSHOT/cobertura-2.1.0-SNAPSHOT.pom
         https://repo1.maven.org/maven2/net/sourceforge/cobertura/cobertura/2.1.0-SNAPSHOT/cobertura-2.1.0-SNAPSHOT.jar
         https://jcenter.bintray.com/net/sourceforge/cobertura/cobertura/2.1.0-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/net/sourceforge/cobertura/cobertura/2.1.0-SNAPSHOT/cobertura-2.1.0-SNAPSHOT.pom
         https://jcenter.bintray.com/net/sourceforge/cobertura/cobertura/2.1.0-SNAPSHOT/cobertura-2.1.0-SNAPSHOT.jar
     Required by:
         com.github.tagc:semver:0.4.1-SNAPSHOT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

This happens for 2.0.4 as well. It does work if I force to version 2.0.3, and the outputted reports from that are similar to what I posted in the original post.

**Comment by stevesaliman** [comment]
You need to tell Gradle to include the Maven Snapshot Repository.  Try adding the following to the "repositories" block of your build.gradle file:
```
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
```
You should then be able to use Cobertura 2.1.  The reason I'm curious to see how Cobertura 2.1 works for you is because they have changed some of the libraries they use to instrument code, and the new libraries seem to play better with Java 8 than the old ones.

**Comment by TAGC** [comment]
Ah, thanks, I hadn't realised snapshots were hosted on a separate repository.

I've tried again with Cobertura 2.1.0-SNAPSHOT. It succeeds, but the generated report is identical to the one shown in the original post.

**Comment by bric3** [comment]
Since a few days I experience the same issue (mockito project), on localhost no problem, however on travis a lot of project's classes fail to load when tests are run with cobertura.

* version : net.saliman:gradle-cobertura-plugin:2.2.5
* cobertura : 2.0.3
* coveralls : org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.1.0
* jdk 1.7u72 (travis)
* java target 1.5

Here's a sample errors reporting my own classes cannot be found ?

```
org.mockito.MockitoTest > shouldRemoveStubbableFromProgressAfterStubbing FAILED
    java.lang.NoClassDefFoundError: Could not initialize class org.mockito.internal.stubbing.answers.AnswersValidator
        at org.mockito.internal.stubbing.InvocationContainerImpl.addAnswer(InvocationContainerImpl.java:60)
        at org.mockito.internal.stubbing.InvocationContainerImpl.addAnswer(InvocationContainerImpl.java:50)
        at org.mockito.internal.stubbing.OngoingStubbingImpl.thenAnswer(OngoingStubbingImpl.java:28)
        at org.mockito.internal.stubbing.BaseStubbing.thenReturn(BaseStubbing.java:18)
        at org.mockito.MockitoTest.shouldRemoveStubbableFromProgressAfterStubbing(MockitoTest.java:24)
```

Could it be linked to this issue https://github.com/cobertura/cobertura/issues/49 ? (we don't use auxiliary classpath in out build script).

Also I have digged a bit more, but I'm still puzzled as how it can happen. The sources are in the same directory.

Cobertura finds classes :

```
17:08:27.091 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] Working on file:/home/travis/build/mockito/mockito/build/instrumented_classes/org/mockito/configuration/AnnotationEngine.class
17:08:27.094 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] =============== Detected duplicated code =============
17:08:27.095 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] =============== End of detected duplicated code ======
17:08:27.095 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] Migrating classmap in projectData to store in *.ser file: org/mockito/configuration/AnnotationEngine
17:08:27.095 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] Class shouldn't be instrumented: org/mockito/configuration/AnnotationEngine
17:08:27.096 [DEBUG] [net.sourceforge.cobertura.instrument.Main] Instrumenting: /home/travis/build/mockito/mockito/build/instrumented_classes/org/mockito/configuration/IMockitoConfiguration.class to null
17:08:27.096 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] Instrumenting class /home/travis/build/mockito/mockito/build/instrumented_classes/org/mockito/configuration/IMockitoConfiguration.class
17:08:27.097 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] Working on file:/home/travis/build/mockito/mockito/build/instrumented_classes/org/mockito/configuration/IMockitoConfiguration.class
17:08:27.099 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] =============== Detected duplicated code =============
17:08:27.099 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] =============== End of detected duplicated code ======
17:08:27.099 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] Migrating classmap in projectData to store in *.ser file: org/mockito/configuration/IMockitoConfiguration
17:08:27.100 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] Class shouldn't be instrumented: org/mockito/configuration/IMockitoConfiguration
17:08:27.100 [DEBUG] [net.sourceforge.cobertura.instrument.Main] Instrumenting: /home/travis/build/mockito/mockito/build/instrumented_classes/org/mockito/configuration/DefaultMockitoConfiguration.class to null
```

Then all of a sudden, it fails.

```
17:08:27.203 [DEBUG] [net.sourceforge.cobertura.instrument.CoberturaInstrumenter] org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 12: java.lang.ClassNotFoundException: org.mockito.stubbing.Answer
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Unknown Source)
	at org.objectweb.asm.util.CheckClassAdapter.verify(Unknown Source)
	at org.objectweb.asm.util.CheckClassAdapter.verify(Unknown Source)
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:208)
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:121)
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:234)
	at net.sourceforge.cobertura.instrument.Main.addInstrumentationToSingleClass(Main.java:298)
	at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:307)
	at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
	at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
	at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
	at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
	at net.sourceforge.cobertura.instrument.Main.parseArguments(Main.java:399)
	at net.sourceforge.cobertura.instrument.Main.main(Main.java:421)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at net.saliman.gradle.plugin.cobertura.CoberturaRunner.executeCobertura(CoberturaRunner.groovy:224)
	at net.saliman.gradle.plugin.cobertura.CoberturaRunner.this$2$executeCobertura(CoberturaRunner.groovy)
	at net.saliman.gradle.plugin.cobertura.CoberturaRunner$this$2$executeCobertura$2.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)
	at net.saliman.gradle.plugin.cobertura.CoberturaRunner.instrument(CoberturaRunner.groovy:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at net.saliman.gradle.plugin.cobertura.InstrumentTask.instrument(InstrumentTask.groovy:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.ParallelTaskPlanExecutor.process(ParallelTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.mockito.stubbing.Answer
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(Unknown Source)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(Unknown Source)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(Unknown Source)
	at org.objectweb.asm.tree.analysis.BasicVerifier.returnOperation(Unknown Source)
	at org.objectweb.asm.tree.analysis.BasicVerifier.returnOperation(Unknown Source)
	at org.objectweb.asm.tree.analysis.Frame.execute(Unknown Source)
	... 113 more
getDefaultAnswer()Lorg/mockito/stubbing/Answer;
```

**Comment by stevesaliman** [comment]
I just released version 2.2.7 of the plugin which uses version 2.1.1 of Cobertura, which in turn updates some of the other libraries used.  Is this still a problem in version 2.2.7?

**Comment by stevesaliman** [comment]
Since I haven't heard back, I'll assume that the latest version of Cobertura fixes this issue.  Feel free to re-open this issue if that is not the case.

**Comment by bric3** [comment]
@stevesaliman sorry for late reply got caught up in something else. It seems it indeed solves these issues. But I still had slf4j issues the issue #75 helped for that (btw it should be in the usage.md)
