### ISSUE TITLE
Unable to parse JDK7 binary literals

### ISSUE THREAD

**Issue by shevek** [stevesaliman/gradle-cobertura-plugin#69]
```
net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " <IDENTIFIER> "b11 "" at line 71, column 37.
Was expecting one of:
    "instanceof" ...
    ")" ...
    "," ...
    "=" ...
    ">" ...
    "<" ...
    "?" ...
    "==" ...
    "<=" ...
    ">=" ...
    "!=" ...
    "||" ...
    "&&" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "&" ...
    "|" ...
    "^" ...
    "%" ...
    "+=" ...
    "-=" ...
    "*=" ...
    "/=" ...
    "&=" ...
    "|=" ...
    "^=" ...
    "%=" ...
    "<<=" ...
    ">>=" ...
    ">>>=" ...
    ">" ...
    
	at net.sourceforge.cobertura.javancss.parser.JavaParser.generateParseException(JavaParser.java:11869)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_consume_token(JavaParser.java:11730)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Arguments(JavaParser.java:3539)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.AllocationExpression(JavaParser.java:3587)
```

**Comment by shevek** [comment]
Test case: https://github.com/shevek/ipmi4j

**Comment by stevesaliman** [comment]
This is a problem with Cobertura itself and will need to be fixed there.  It is referenced in several issues in the Cobertura repo, but I think https://github.com/cobertura/cobertura/issues/176 is the one that is still open.
